spring:
    profiles.active: default
---
spring:
    profiles: default
spring.datasource:
    url: jdbc:postgresql://{{{postgres_url}}}/spatial
    username: {{{postgres_admin}}}
    password: {{{postgres_password}}}
    maxActive: 20
    maxIdle: 20 
spring.jpa:
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.properties.hibernate:
    default_schema: wiyby_data
